---
- name: reboot_machine
  command: reboot "Reboot triggered by Ansible"
  async: 0
  poll: 0
  ignore_errors: true

- name: wait_for_bootup
  local_action:
    module: wait_for
      host={{ inventory_hostname }}
      port=22
      delay=1
      timeout=300